"""init

Revision ID: 33328513c384
Revises: 
Create Date: 2018-05-21 17:37:07.711677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33328513c384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorid', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['authorid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_created'), 'image', ['created'], unique=False)
    op.create_table('like',
    sa.Column('authorid', sa.String(), nullable=True),
    sa.Column('imageid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['user.userid'], ),
    sa.ForeignKeyConstraint(['imageid'], ['image.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_index(op.f('ix_image_created'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
